### ISSUE TITLE
Calling dispose() on a Wrapper Object leads to memory leak

### ISSUE THREAD

**Issue by ChristianHoesel** [kohsuke/com4j#16]
After calling dispose() the NativePointerPhantomReference of a Wrapper object will not be removed form the list of liveComObject in the ComThread.

**Comment by Petikoch** [comment]
@kohsuke is there somewhere a release to download containing this fix? 

In https://github.com/kohsuke/com4j/downloads (referenced by http://com4j.kohsuke.org/) I see only an "old" com4j-20120426-2.zip package.
