### ISSUE TITLE
BStr* support problem.

### ISSUE THREAD

**Issue by mdre** [kohsuke/com4j#42]
Hi all! 
I'am having problem mapping a COM library from ZKSoftware to access the VF600 IFace clock. 
The method header is:

VARIANT_BOOL SSR_GetGeneralLogData(
 [in] LONG dwMachineNumber, 
[out] BSTR* dwEnrollNumber, 
[out] LONG* dwVerifyMode, [out] LONG* dwInOutMode, [out] LONG* dwYear, [out] LONG* dwMonth, [out] LONG* dwDay, [out] LONG* dwHour, [out] LONG*
dwMinute, [out] LONG* dwSecond, [out] LONG* dwWorkcode)

and com4j generate:

@DISPID(145) //= 0x91. The runtime will prefer the VTID if present
  @VTID(153)
  boolean ssR_GetGeneralLogData(
    int dwMachineNumber,
    Holder<java.lang.String> dwEnrollNumber,
    Holder<Integer> dwVerifyMode,
    Holder<Integer> dwInOutMode,
    Holder<Integer> dwYear,
    Holder<Integer> dwMonth,
    Holder<Integer> dwDay,
    Holder<Integer> dwHour,
    Holder<Integer> dwMinute,
    Holder<Integer> dwSecond,
    Holder<Integer> dwWorkCode);

Other methods works and I suspect that the problems is the BSTR* pointer. Tha JVM blow up when the program reach function call. 
Does sombothy know any workaround? 
Thanks!

 Marcelo

**Comment by mdre** [comment]
I found the problem! The library work fine. The error was in my code. I have misplaced a call parameter.

**Comment by parkererik** [comment]
Hi @mdre, any chance you could share your findings? I'm having a similar issue calling a BSTR* parameter. Thanks!

**Comment by mdre** [comment]
Hi Erik!
What do you need? The wrapper itself?
Because the problem that I had was trivial, just misplaced the call
parameters, and I have not documented it.
If you need the wrapped code have no problem to share it.

Marcelo

**Comment by parkererik** [comment]
Hey thanks for your reply! Would you be able to share how you're calling the SSR_GetGeneralLogData method? Specifically how you're passing in the dwEnrollNumber parameter. Thanks!

**Comment by mdre** [comment]
Look at line 120.
That file was a simple lab test that I was using at that time. Some thing
are not related with com4j.
I never could retrieve the photo from the VF600 divice.

**Comment by parkererik** [comment]
Thanks again Marcelo-- do you mean 120 of one of the com4j files? Or did you mean to attach something?

**Comment by mdre** [comment]
In the attached file. ZKtest.java. Do you receive it?

**Comment by parkererik** [comment]
Hey sorry Marcelo, no attachment. Maybe because you're sending through email? The GitHub web interface lets you drag a file to attach. Or you can just copy and paste the relevant section, whatever's easier! Thanks again.
